### ISSUE TITLE
Maiskolben (Kaufversion v2.0) Bootet nicht mehr

### ISSUE THREAD

**Issue by DrKuebel** [ArduinoHannover/Maiskolben#4]
Hallo,

wenn der MK mit 12V versorgt wird, leuchtet das Display konstat weiss auf und die Power LED blinkt 5 mal kurz auf... mehr passiert nicht.

woran kann das liegen?

**Comment by soundstorm** [comment]
Hallo,

einige Displays haben etwas Probleme damit, wenn die Pegel nicht schnell genug auf dem richtigen Level sind. Durch ein länger auf LOW gehaltenen Reset des Displays lässt sich hier Abhilfe schaffen:
https://github.com/ArduinoHannover/Maiskolben/blob/master/Maiskolben_Mechanical/Maiskolben_Displayfix.pdf
Alternativ kann auch STBY unten links auf der Platine mit dem im PDF gezeigten Pin am 4050 verbunden werden, auch hierbei muss die Leitung nach oben (da wo der 10k sonst rein sollte) getrennt werden. In der Software muss dann `#define USE_TFT_RESET` gesetzt werden:
https://github.com/ArduinoHannover/Maiskolben/blob/master/Maiskolben_Mechanical/README.md

**Comment by DrKuebel** [comment]
Hallo,

Danke für die schnelle Antwort
Die von Dir angesprochene Änderung war schon eingelötet in der gelieferten Platine.

s.Foto

Gruß

![img_5124](https://user-images.githubusercontent.com/25255280/34097891-e1e535ce-e3da-11e7-938b-a936f87a20e3.JPG)

**Comment by DrKuebel** [comment]
![img_e5135](https://user-images.githubusercontent.com/25255280/34154297-462fd2fc-e4b5-11e7-98a9-b143e3815901.JPG)
Hallo,

wenn ich das richtig verstanden habe, muss ich die beiden Bauteile (gelb) entfernen und statt dessen eine Verbindung (blau) an den Lötpunkt (grün) legen.

Gruß

**Comment by soundstorm** [comment]
Hallo,

genau, dies wäre mit einem Softwareupdate verbunden. Alternativ lässt sich auch der Widerstandswert erhöhen (aktuell sind 68k eingebaut).
Zunächst sollte aber geprüft werden, ob mit einem regulären Reset per rotem Taster die Initialisierung korrekt abläuft.

**Comment by DrKuebel** [comment]
Hallo,

wenn ich den roten Reset an der Unterseite drücke passiert das gleiche , LED blinkt 5 mal und Bildschirm bleibt weiss.

Gruß

**Comment by soundstorm** [comment]
Es könnte ggf. zum Ziel führen, allerdings könnte sich auch eventuell die Reset-Leitung Richtung Display gelöst haben. Sollte letzteres der Fall sein, so wird diese Lösung nicht helfen. Einen Versuch ist es jedoch wert.
Wenn der Maiskolben über USB versorgt wird, tritt das Problem ebenso auf?

**Comment by DrKuebel** [comment]
gelegentlich bootet er am Win10 USB.  Am Mac bootet er in den "whitescreen"
