### ISSUE TITLE
Blaue Schrift

### ISSUE THREAD

**Issue by bin101** [ArduinoHannover/Maiskolben#6]
Hallo zusammen,

ich habe den Maiskolben HW v3.1 welcher angeblich mit der Software Version 3.0 ausgeliefert wurde.
Angeblich deshalb, da folgender Punkt:
°C wird mit bei Soll- und Ist-Temperatur angezeigt
Bei mir so nicht zutraf.

Nun wollte ich halt die neueste Version installieren, hat soweit auch alles geklappt. Nur die Tatsache, dass alles in blau ausgegeben wird stört mich ein wenig:
![maiskolben](https://user-images.githubusercontent.com/12427722/35100312-af0184de-fc5b-11e7-8bd2-4322d759022c.png)

Ob ich nun HARDWARE_DEFINED_TFT auf 1 oder 2 setzte, das display setup mit der Blau/Rot Auswahl erzwinge und entsprechend bediene oder ob ich manuell den EEPROM mit RGB_DISP oder BGR_DISP beschreibe (dazu dann passend die Ausführung von setDisplayMode()) ändert leider nichts am Ergebnis und daher wollte ich hier um Hilfe fragen.

Mittlerweile habe ich eher das Gefühl, dass bei mir ein anderer TFT verbaut wurde...

**Comment by bin101** [comment]
Problem gefunden:
https://github.com/ArduinoHannover/TFT_ILI9163C/commit/5ae286158f478392a631815083528f7955a27767

den colorSpace einfach nur public zu machen scheint so nicht zu funktionieren.

**Comment by soundstorm** [comment]
Die letzten Änderungen wurden zwar committed aber nicht gepusht. Habe ich nachgeholt, sollte jetzt klappen 🙈

**Comment by bin101** [comment]
Jupp das hat geholfen ;)
