### ISSUE TITLE
kann Maiskolben_TFT nicht kompilieren

### ISSUE THREAD

**Issue by andreasloe** [ArduinoHannover/Maiskolben#7]
Ich habe folgendes Problem und komme leider nicht weiter:

- Ich habe die Fehlermeldung in eine text-datei kopiert, das sieht ja sonst unmöglich aus. -
[Fehlermeldung.txt](https://github.com/ArduinoHannover/Maiskolben/files/1957902/Fehlermeldung.txt)

**Comment by soundstorm** [comment]
Der Maiskolben ist leider nicht auf einem ESP8266 lauffähig ;-)

**Comment by andreasloe** [comment]
Sorry, dann brauche ich Nachhilfe. Ich habe den vor vier Wochen gekauft und gar nicht versucht nachzubauen. Ich will den nur kompilieren, mit der arduino IDE. Anscheinend mache ich da was völlig falsch. Ich dachte, ich muss "Generic ESP8266" einstellen, was offensichtlich falsch ist. Was stelle ich ein?

**Comment by soundstorm** [comment]
Nein, Arduino Nano, ATmega328 (old bootloader) :)

**Comment by andreasloe** [comment]
Danke!
